[package]
name = "bs64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.21.0"
data-encoding = "2.3.3"
thiserror = "1.0.49"
rand = "0.8.5"
